/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BitCoinTable: typeof import('./src/components/BitCoinTable.vue')['default']
    BondsTable: typeof import('./src/components/BondsTable.vue')['default']
    CommoditiesTable: typeof import('./src/components/CommoditiesTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ForexTable: typeof import('./src/components/ForexTable.vue')['default']
    OffshoreRMB: typeof import('./src/components/OffshoreRMB.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    StockEcharts: typeof import('./src/components/StockEcharts.vue')['default']
    StockIndexTable: typeof import('./src/components/StockIndexTable.vue')['default']
    StockTable: typeof import('./src/components/StockTable.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
