/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AnalysisFinancialDataKinds: typeof import('./src/components/AnalysisFinancialDataKinds.vue')['default']
    AnalysisTwoFinancialData: typeof import('./src/components/AnalysisTwoFinancialData.vue')['default']
    BitCoinEcharts: typeof import('./src/components/BitCoinEcharts.vue')['default']
    BitCoinTable: typeof import('./src/components/BitCoinTable.vue')['default']
    BondsEchats: typeof import('./src/components/BondsEchats.vue')['default']
    BondsTable: typeof import('./src/components/BondsTable.vue')['default']
    CommoditiesEcharts: typeof import('./src/components/CommoditiesEcharts.vue')['default']
    CommoditiesTable: typeof import('./src/components/CommoditiesTable.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Footer: typeof import('./src/components/Footer.vue')['default']
    ForexEcharts: typeof import('./src/components/ForexEcharts.vue')['default']
    ForexTable: typeof import('./src/components/ForexTable.vue')['default']
    OffshoreRMBEcharts: typeof import('./src/components/OffshoreRMBEcharts.vue')['default']
    OffshoreRMBTable: typeof import('./src/components/OffshoreRMBTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectAnalysisFinancialData: typeof import('./src/components/SelectAnalysisFinancialData.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    StockEcharts: typeof import('./src/components/StockEcharts.vue')['default']
    StockIndexEcharts: typeof import('./src/components/StockIndexEcharts.vue')['default']
    StockIndexTable: typeof import('./src/components/StockIndexTable.vue')['default']
    StockTable: typeof import('./src/components/StockTable.vue')['default']
    TopBar: typeof import('./src/components/TopBar.vue')['default']
  }
}
